name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, 'skip') && contains(github.event.head_commit.message, 'ci'))"
    steps:
      - name: Prepare
        run: ''

  build:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.5.3'

      - name: Check Flutter version
        run: flutter --version

      - name: Restore dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build (Web)
        run: flutter build web --web-renderer canvaskit

      - name: Test
        run: flutter test

      - name: Format
        if: ${{ github.event_name != 'pull_request' }}
        run: flutter format --set-exit-if-changed ./

      - name: Analyze
        if: ${{ github.event_name != 'pull_request' }}
        run: flutter analyze

      - name: Format and Report
        if: ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: flutter format ./ > flutter_format_report.txt

      - name: Analyze and Report
        if: ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: flutter analyze > flutter_analyze_report.txt

      - name: Run Danger
        if: ${{ github.event_name == 'pull_request' }}
        uses: danger/danger-js@9.1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
